name: Publish

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 3 * * *"

jobs:
  publish-latest:
    name: Build & publish latest
    runs-on: ubuntu-latest
    env:
      IMAGE: roobre/infrastructure-k8s-lite:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build . -t $IMAGE
      - uses: docker/login-action@v1
        with:
          username: roobre
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Upload docker images
        run: |
          docker push $IMAGE

  publish-master:
    name: Build & publish master
    runs-on: ubuntu-latest
    env:
      IMAGE: roobre/infrastructure-k8s-lite:master
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Clone upstream repo
        run: |
          git clone https://github.com/newrelic/nri-kubernetes
      - name: Build upstream master
        working-directory: nri-kubernetes
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go mod download
          make compile
          docker build . -t newrelic/infrastructure-k8s:master
      - name: Build docker image
        run: |
          docker build . -t $IMAGE --build-arg UPST_TAG=master
      - uses: docker/login-action@v1
        with:
          username: roobre
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Upload docker images
        run: |
          docker push $IMAGE
