name: Publish

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 3 * * *"

jobs:
  patch-latest:
    name: Build & publish latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [ latest, latest-unprivileged ]
    env:
      IMAGE: roobre/infrastructure-k8s-lite
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: roobre
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: |
          docker build . -t ${IMAGE}:${{ matrix.tag }} --build-arg UPST_TAG=${{ matrix.tag }}
      - name: Upload docker images
        run: |
          docker push ${IMAGE}:${{ matrix.tag }}

  patch-master:
    name: Build & publish master from sources
    runs-on: ubuntu-latest
    env:
      IMAGE: roobre/infrastructure-k8s-lite:master
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Clone upstream repo
        run: |
          git clone https://github.com/newrelic/nri-kubernetes
      - name: Patch definition
        run: |
          cp nri-kubernetes-definition.yml nri-kubernetes/
      - uses: docker/login-action@v1
        with:
          username: roobre
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Patch and build upstream master
        working-directory: nri-kubernetes
        env:
          GOOS: linux
          GOARCH: amd64
          DOCKER_BUILDKIT: 1
        run: |
          go mod download
          make compile
          docker build . -t $IMAGE
          docker build . -t $IMAGE-unprivileged --build-arg 'MODE=unprivileged'
      - name: Upload docker images
        run: |
          docker push $IMAGE
          docker push $IMAGE-unprivileged
