name: Publish

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 3 * * *"

jobs:
  publish:
    name: Build & publish docker image
    runs-on: ubuntu-latest
    env:
      IMAGE: roobre/infrastructure-k8s-lite
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build -t $IMAGE .
      - uses: docker/login-action@v1
        with:
          username: roobre
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Upload docker images
        run: |
          docker push $IMAGE
